version: '2'

services:
  yolo-gpu:
    build: 
      context: .
      dockerfile: Dockerfile.gpu
    entrypoint: bash
    image: yolo:gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  yolo-cpu:
    build: 
      context: .
      dockerfile: Dockerfile.cpu
    entrypoint: python3 /dnshare/server/server_all.py #Relative pathing. Only change if you have also changed the path of the volume inside your container
    image: yolo:cpu
    volumes:
        # */zebrai/dnshare:/dnshare:rw
      - /ltstorage/shares/projects/zebrai/dnshare:/dnshare:rw # TODO Configure the absolute path of the volume on your machine/server
    ports:
      - "5656:5000" #Port 5656 can be configured
